if (NOT LIBCLANG_ROOT_DIR)
    set(LIBCLANG_ROOT_DIR $ENV{LIBCLANG_ROOT_DIR})
endif ()

if (NOT EXISTS ${LIBCLANG_INCLUDEDIR})
    set(LIBCLANG_INCLUDEDIR ${LIBCLANG_ROOT_DIR}/include)
endif ()

if (NOT LIBCLANG_CXXFLAGS)
    set(LIBCLANG_CXXFLAGS "-I${LIBCLANG_INCLUDEDIR}")
endif ()

if (NOT EXISTS ${LIBCLANG_LIBDIR})
    set(LIBCLANG_LIBDIR ${LIBCLANG_ROOT_DIR}/lib)
endif ()

if (NOT LIBCLANG_LIBRARIES)
    set (LIBCLANG_LIBRARIES "-L${LIBCLANG_LIBDIR}" "-lclang" "-Wl,-rpath,${LIBCLANG_LIBDIR}")
endif ()
